export {default as Home} from './home'
export {default as About} from './about'
export {default as Contact} from './contact'
export {default as Pricing} from './pricing'
export {default as Terms} from './terms'